create database javaee_training;

use javaee_training;

drop table gd_login;

CREATE TABLE GD_LOGIN
(
  LOGIN_ID VARCHAR(200),
  PASSWORD VARCHAR(200),
  ROLE VARCHAR(20)
);

INSERT INTO GD_LOGIN VALUES('N001','123','normal');
INSERT INTO GD_LOGIN VALUES('N002','123','normal');
INSERT INTO GD_LOGIN VALUES('N003','123','normal');
INSERT INTO GD_LOGIN VALUES('N004','123','normal');
INSERT INTO GD_LOGIN VALUES('N005','123','normal');

INSERT INTO GD_LOGIN VALUES('A001','123','admin');
INSERT INTO GD_LOGIN VALUES('A002','123','admin');
INSERT INTO GD_LOGIN VALUES('A003','123','admin');
INSERT INTO GD_LOGIN VALUES('A004','123','admin');
INSERT INTO GD_LOGIN VALUES('A005','123','admin');

COMMIT;
SELECT * FROM GD_Login order by 1;